# Generated by Django 5.2.8 on 2025-12-22 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0015_repositoryassignment'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('commit_hash', models.CharField(blank=True, help_text='Git commit hash at time of evaluation', max_length=40, null=True)),
                ('branch', models.CharField(default='main', help_text='Branch evaluated', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Error message if evaluation failed', null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID', max_length=255, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_evaluations', to='repositories.repository')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='standards.compliancestandard')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered this evaluation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Evaluation',
                'verbose_name_plural': 'Compliance Evaluations',
                'db_table': 'cpl_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='compliance.complianceevaluation')),
                ('total_score', models.DecimalField(decimal_places=2, help_text='Percentage score (0-100)', max_digits=5)),
                ('passed_weight', models.PositiveIntegerField(help_text='Sum of weights for passed rules')),
                ('total_weight', models.PositiveIntegerField(help_text='Sum of weights for all evaluated rules')),
                ('passed_count', models.PositiveIntegerField(help_text='Number of rules that passed')),
                ('failed_count', models.PositiveIntegerField(help_text='Number of rules that failed')),
                ('total_rules', models.PositiveIntegerField(help_text='Total number of rules evaluated')),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score from previous evaluation (for trend)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Score',
                'verbose_name_plural': 'Compliance Scores',
                'db_table': 'cpl_scores',
            },
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(help_text='Whether the rule check passed')),
                ('evidence', models.JSONField(default=dict, help_text='Evidence captured during the rule check')),
                ('message', models.TextField(blank=True, help_text='Human-readable message explaining the result')),
                ('weight', models.PositiveIntegerField(help_text='Weight of this rule at time of evaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='compliance.complianceevaluation')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='standards.compliancerule')),
            ],
            options={
                'verbose_name': 'Rule Result',
                'verbose_name_plural': 'Rule Results',
                'db_table': 'cpl_rule_results',
                'ordering': ['evaluation', 'rule__order'],
            },
        ),
        migrations.AddIndex(
            model_name='complianceevaluation',
            index=models.Index(fields=['repository', 'status'], name='cpl_evaluat_reposit_36506f_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevaluation',
            index=models.Index(fields=['repository', 'standard', '-created_at'], name='cpl_evaluat_reposit_3887c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruleresult',
            unique_together={('evaluation', 'rule')},
        ),
    ]
