# Generated by Django 5.2.8 on 2026-01-08 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='repositories.repository')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=64)),
                ('rule_id', models.CharField(max_length=128)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('raw_output', models.JSONField(default=dict, help_text='Original scanner output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan')),
            ],
            options={
                'db_table': 'scan_findings',
                'ordering': ['-severity', 'file_path'],
                'indexes': [models.Index(fields=['severity'], name='scan_findin_severit_de5dae_idx'), models.Index(fields=['tool'], name='scan_findin_tool_d49600_idx')],
            },
        ),
    ]
