# Generated by Django 5.2.8 on 2026-01-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0, help_text='Scan progress percentage 0-100'),
        ),
        migrations.AddField(
            model_name='scan',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
