# Generated by Django 5.2.8 on 2026-01-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanfinding',
            options={'ordering': ['-severity', 'file_path']},
        ),
        migrations.RenameField(
            model_name='scanfinding',
            old_name='line',
            new_name='line_number',
        ),
        migrations.RemoveField(
            model_name='scanfinding',
            name='message',
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='description',
            field=models.TextField(default='No description', help_text='Detailed description of the issue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='raw_output',
            field=models.JSONField(default=dict, help_text='Original scanner output'),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='title',
            field=models.TextField(default='No title', help_text='Short title of the finding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='tool',
            field=models.CharField(default='unknown', help_text='Scanner tool name (bandit, secret_scanner, etc.)', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanfinding',
            name='rule_id',
            field=models.CharField(help_text='Rule identifier from scanner', max_length=128),
        ),
        migrations.AlterField(
            model_name='scanfinding',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scanfinding',
            index=models.Index(fields=['severity'], name='scan_findin_severit_de5dae_idx'),
        ),
        migrations.AddIndex(
            model_name='scanfinding',
            index=models.Index(fields=['tool'], name='scan_findin_tool_d49600_idx'),
        ),
        migrations.AlterModelTable(
            name='scanfinding',
            table='scan_findings',
        ),
    ]
