# Generated by Django 5.2.8 on 2026-01-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scanfinding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the security issue', max_length=255)),
                ('explanation', models.TextField(help_text='Detailed explanation of the vulnerability')),
                ('fix_code', models.TextField(help_text='Code fix suggestion with examples')),
                ('references', models.JSONField(default=list, help_text='List of reference links and standards')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('service_version', models.CharField(default='1.0.0', max_length=50)),
                ('finding', models.OneToOneField(help_text='The scan finding this analysis is for', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='scans.scanfinding')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'db_table': 'ai_analyses',
                'ordering': ['-generated_at'],
            },
        ),
    ]
