# Generated by Django 5.2.8 on 2026-01-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_chat_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='finding',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
        migrations.DeleteModel(
            name='ChatConversation',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
