# Generated by Django 5.2.8 on 2025-12-22 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_tenantmember_deleted_at_and_more'),
        ('compliance', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('trigger', 'Triggered'), ('complete', 'Completed'), ('fail', 'Failed'), ('assign', 'Assigned'), ('unassign', 'Unassigned')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(help_text='Organization this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'aud_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='aud_logs_organiz_96539f_idx'), models.Index(fields=['actor', '-created_at'], name='aud_logs_actor_i_29a401_idx'), models.Index(fields=['content_type', 'object_id'], name='aud_logs_content_a55587_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('file_check', 'File Existence Check'), ('folder_check', 'Folder Existence Check'), ('config_check', 'Configuration Check'), ('repo_metadata', 'Repository Metadata'), ('commit_info', 'Commit Information')], db_index=True, max_length=30)),
                ('target_path', models.CharField(blank=True, help_text='File path or identifier being checked', max_length=500)),
                ('captured_data', models.JSONField(default=dict, help_text='Data captured during the check')),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 hash of file content (for file checks)', max_length=64)),
                ('content_snippet', models.TextField(blank=True, help_text='First N characters of file content (for documentation files)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='compliance.complianceevaluation')),
            ],
            options={
                'verbose_name': 'Evaluation Evidence',
                'verbose_name_plural': 'Evaluation Evidence',
                'db_table': 'aud_evidence',
                'ordering': ['evaluation', 'evidence_type', 'target_path'],
                'indexes': [models.Index(fields=['evaluation', 'evidence_type'], name='aud_evidenc_evaluat_b8b951_idx')],
            },
        ),
    ]
