# Generated by Django 5.2.8 on 2025-12-22 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_tenantmember_deleted_at_and_more'),
        ('repositories', '0015_repositoryassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Human-readable name of the standard', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the standard's purpose")),
                ('version', models.CharField(default='1.0', help_text='Version of the standard', max_length=20)),
                ('is_builtin', models.BooleanField(db_index=True, default=False, help_text='True if this is a platform-provided standard')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this standard is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization that created this custom standard (null for built-in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_standards', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Compliance Standard',
                'verbose_name_plural': 'Compliance Standards',
                'db_table': 'std_compliance_standards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of the rule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of why this rule matters')),
                ('rule_type', models.CharField(choices=[('file_exists', 'Required File'), ('file_forbidden', 'Forbidden File'), ('folder_exists', 'Required Folder'), ('config_check', 'Configuration Check'), ('pattern_match', 'Pattern Match'), ('hygiene', 'Repository Hygiene')], db_index=True, help_text='Type of check to perform', max_length=30)),
                ('check_config', models.JSONField(default=dict, help_text='Configuration for the rule check (JSON)')),
                ('weight', models.PositiveIntegerField(default=5, help_text='Weight of this rule in score calculation (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Importance level of this rule', max_length=20)),
                ('remediation_hint', models.TextField(blank=True, help_text='Guidance on how to fix a failed rule')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the standard')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this rule is enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='standards.compliancestandard')),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'db_table': 'std_compliance_rules',
                'ordering': ['standard', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this standard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_assignments', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_standards', to='repositories.repository')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_repositories', to='standards.compliancestandard')),
            ],
            options={
                'verbose_name': 'Repository Standard',
                'verbose_name_plural': 'Repository Standards',
                'db_table': 'std_repository_standards',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='compliancestandard',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_builtin', True), ('organization__isnull', True)), models.Q(('is_builtin', False), ('organization__isnull', False)), _connector='OR'), name='standard_builtin_or_org'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancerule',
            unique_together={('standard', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='repositorystandard',
            unique_together={('repository', 'standard')},
        ),
    ]
