# Generated by Django 5.2.8 on 2026-01-08 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this credential', max_length=255)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('azure', 'Azure DevOps')], db_index=True, default='github', max_length=20)),
                ('encrypted_access_token', models.TextField(help_text='Encrypted OAuth access token')),
                ('github_installation_id', models.CharField(blank=True, help_text='GitHub App installation ID', max_length=255, null=True)),
                ('github_account_login', models.CharField(blank=True, help_text='GitHub account/organization login', max_length=255, null=True)),
                ('github_account_id', models.CharField(blank=True, help_text='GitHub account/organization ID', max_length=255, null=True)),
                ('granted_scopes', models.TextField(blank=True, help_text='OAuth scopes granted (comma-separated)', null=True)),
                ('oauth_data', models.JSONField(blank=True, default=dict, help_text='Additional OAuth metadata')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_credentials', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Credential',
                'verbose_name_plural': 'Tenant Credentials',
                'db_table': 'tenant_credentials',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_scanned_commit', models.CharField(blank=True, help_text='SHA hash of the last scanned commit', max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.tenant')),
                ('credential', models.ForeignKey(blank=True, help_text='Credential used for repository access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='repositories.tenantcredential')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'url')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this repository', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repositories', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='Developer assigned to this repository', on_delete=django.db.models.deletion.CASCADE, related_name='repository_assignments', to='accounts.tenantmember')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Repository Assignment',
                'verbose_name_plural': 'Repository Assignments',
                'db_table': 'repository_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('repository', 'member')},
            },
        ),
    ]
