# Generated by Django 5.2.8 on 2025-12-04 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_organiz_c1b1ad_idx',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='organization',
            new_name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('tenant', 'url')},
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['tenant', 'is_active'], name='repositorie_tenant__188b4d_idx'),
        ),
    ]
