# Generated by Django 5.2.8 on 2026-01-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='webhook_id',
            field=models.CharField(blank=True, help_text='GitHub webhook ID for automatic scanning', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='HMAC secret for webhook signature validation', max_length=64, null=True),
        ),
    ]
