# Generated by Django 5.2.8 on 2025-12-09 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_change_user_tenant_to_onetoone'),
        ('repositories', '0002_remove_repository_repositorie_organiz_c1b1ad_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField()),
                ('token_scope', models.CharField(max_length=100)),
                ('encryption_key_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Repository Token',
                'verbose_name_plural': 'Repository Tokens',
                'db_table': 'repository_tokens',
            },
        ),
        migrations.CreateModel(
            name='RepositoryValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(choices=[('access', 'Access Validation'), ('permissions', 'Permission Check'), ('metadata', 'Metadata Collection'), ('webhook', 'Webhook Setup')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], db_index=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Repository Validation Log',
                'verbose_name_plural': 'Repository Validation Logs',
                'db_table': 'repository_validation_logs',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token', models.TextField()),
                ('token_scope', models.CharField(max_length=100)),
                ('encryption_key_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tenant Token',
                'verbose_name_plural': 'Tenant Tokens',
                'db_table': 'tenant_tokens',
            },
        ),
        migrations.CreateModel(
            name='TokenAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Token Created'), ('read', 'Token Retrieved'), ('update', 'Token Updated'), ('delete', 'Token Deleted'), ('decrypt', 'Token Decrypted'), ('use', 'Token Used')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Audit Log',
                'verbose_name_plural': 'Token Audit Logs',
                'db_table': 'token_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='auth_method',
            field=models.CharField(choices=[('none', 'No Authentication'), ('repo_token', 'Repository Token'), ('tenant_token', 'Tenant Default Token')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='available_branches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='repository_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='repository',
            name='validation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('valid', 'Valid Access'), ('invalid', 'Access Failed'), ('expired', 'Token Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['tenant', 'validation_status'], name='repositorie_tenant__2d90c0_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['tenant', 'auth_method'], name='repositorie_tenant__7a3cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['validation_status', 'last_validated_at'], name='repositorie_validat_bbfb12_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['webhook_enabled'], name='repositorie_webhook_2dbfac_idx'),
        ),
        migrations.AddField(
            model_name='repositorytoken',
            name='repository',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='repositories.repository'),
        ),
        migrations.AddField(
            model_name='repositoryvalidationlog',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='repositories.repository'),
        ),
        migrations.AddField(
            model_name='repositoryvalidationlog',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenanttoken',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_token', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='tokenauditlog',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_audit_logs', to='repositories.repository'),
        ),
        migrations.AddField(
            model_name='tokenauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_audit_logs', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='tokenauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='repositorytoken',
            index=models.Index(fields=['repository'], name='repository__reposit_b08bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='repositorytoken',
            index=models.Index(fields=['expires_at'], name='repository__expires_653ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='repositorytoken',
            index=models.Index(fields=['last_used_at'], name='repository__last_us_95fc44_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoryvalidationlog',
            index=models.Index(fields=['repository', 'validation_type'], name='repository__reposit_1a24b3_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoryvalidationlog',
            index=models.Index(fields=['repository', 'status'], name='repository__reposit_6d54f8_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoryvalidationlog',
            index=models.Index(fields=['validated_at'], name='repository__validat_f6f07a_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoryvalidationlog',
            index=models.Index(fields=['status', 'validated_at'], name='repository__status_9c5f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttoken',
            index=models.Index(fields=['tenant'], name='tenant_toke_tenant__bcff6c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttoken',
            index=models.Index(fields=['expires_at'], name='tenant_toke_expires_83bf73_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanttoken',
            index=models.Index(fields=['last_used_at'], name='tenant_toke_last_us_4401c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenauditlog',
            index=models.Index(fields=['tenant', 'action'], name='token_audit_tenant__fa8ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenauditlog',
            index=models.Index(fields=['repository', 'action'], name='token_audit_reposit_591b56_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenauditlog',
            index=models.Index(fields=['user', 'action'], name='token_audit_user_id_d89e45_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenauditlog',
            index=models.Index(fields=['timestamp'], name='token_audit_timesta_2c7bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='token_audit_action_f6d349_idx'),
        ),
    ]
