# Generated by Django 5.2.8 on 2025-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_enhanced_repository_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorytoken',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='repositoryvalidationlog',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='repositoryvalidationlog',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='tenanttoken',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tokenauditlog',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='tokenauditlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tokenauditlog',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_tenant__2d90c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_tenant__7a3cc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_validat_bbfb12_idx',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_webhook_2dbfac_idx',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='validation_error',
            new_name='encrypted_access_token',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='last_validated_at',
            new_name='github_updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='available_branches',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='repository_metadata',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='validation_status',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='webhook_enabled',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='webhook_secret',
        ),
        migrations.AddField(
            model_name='repository',
            name='connection_type',
            field=models.CharField(choices=[('manual', 'Manual URL Entry'), ('github_oauth', 'GitHub OAuth')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_forks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RepositoryToken',
        ),
        migrations.DeleteModel(
            name='RepositoryValidationLog',
        ),
        migrations.DeleteModel(
            name='TenantToken',
        ),
        migrations.DeleteModel(
            name='TokenAuditLog',
        ),
    ]
