# Generated by Django 5.2.8 on 2025-12-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_remove_repositorytoken_repository_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_github__05e23b_idx',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='encrypted_access_token',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_description',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_forks',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_language',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_stars',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='github_updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='token_expires_at',
        ),
    ]
