# Generated by Django 5.2.8 on 2025-12-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0007_add_assignment_tracking'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repository',
            name='repositories_validation_status_idx',
        ),
        migrations.RenameIndex(
            model_name='repositoryassignment',
            new_name='repository__develop_fe1e55_idx',
            old_name='repositories_repositoryassignment_dev_active_idx',
        ),
        migrations.RenameIndex(
            model_name='repositoryassignment',
            new_name='repository__assigne_4c9989_idx',
            old_name='repositories_repositoryassignment_assigned_at_idx',
        ),
        migrations.RenameIndex(
            model_name='repositoryassignment',
            new_name='repository__reposit_b2dae0_idx',
            old_name='repositories_repositoryassignment_repo_active_idx',
        ),
    ]
