# Generated by Django 5.2.8 on 2025-12-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_change_user_tenant_to_onetoone'),
        ('repositories', '0008_remove_repository_repositories_validation_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRepositoryCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], db_index=True, default='github', max_length=20)),
                ('name', models.CharField(help_text="Human-readable label for this credential (e.g., 'Main GitHub PAT')", max_length=255)),
                ('encrypted_access_token', models.TextField(blank=True, help_text='Fernet-encrypted access token', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive credentials cannot be used for new operations')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last time token was verified against provider API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_credentials', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_credentials', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Repository Credential',
                'verbose_name_plural': 'Repository Credentials',
                'db_table': 'tenant_repository_credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='Tenant credential used for private repository access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='repositories.tenantrepositorycredential'),
        ),
        migrations.AddIndex(
            model_name='tenantrepositorycredential',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_repo_tenant__a9e2be_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantrepositorycredential',
            index=models.Index(fields=['tenant', 'provider'], name='tenant_repo_tenant__c951c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantrepositorycredential',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_credential_name_per_tenant'),
        ),
    ]
