# Generated by Django 5.2.8 on 2025-12-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0009_tenant_repository_credential'),
    ]

    operations = [
    ]
