# Generated by Django 5.2.8 on 2025-12-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0013_add_oauth_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repository',
            name='repositorie_tenant__188b4d_idx',
        ),
    ]
