# Generated by Django 5.2.8 on 2025-12-16 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantmember_deleted_at_and_more'),
        ('repositories', '0014_remove_repository_repositorie_tenant__188b4d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this repository', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_repositories', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='Developer assigned to this repository', on_delete=django.db.models.deletion.CASCADE, related_name='repository_assignments', to='accounts.tenantmember')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Repository Assignment',
                'verbose_name_plural': 'Repository Assignments',
                'db_table': 'repository_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('repository', 'member')},
            },
        ),
    ]
