# Generated by Django 5.2.8 on 2026-01-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0015_repositoryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_scanned_commit',
            field=models.CharField(blank=True, help_text='SHA hash of the last scanned commit', max_length=40, null=True),
        ),
    ]
